name: Publish Farangis Expo Go update

on:
  push:
    branches: ['main']

jobs:
  publish_update:
    name: Publish Farangis iOS update
    type: update
    params:
      branch: main
      platform: ios
      message: Farangis Persian female TTS fix
